# Generated by Django 3.0.7 on 2020-07-07 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0003_auto_20200707_1050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienti',
            name='nr_registrul_comertului',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clienti',
            name='punct_de_lucru',
            field=models.ManyToManyField(blank=True, null=True, to='contr_clienti.Adresa'),
        ),
    ]
