# Generated by Django 3.0.7 on 2020-07-08 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0004_auto_20200707_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienti',
            name='punct_de_lucru',
            field=models.ManyToManyField(blank=True, to='contr_clienti.Adresa'),
        ),
    ]
