# Generated by Django 3.0.7 on 2020-07-21 11:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0005_auto_20200708_1122'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='ContractScan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('documente', models.FileField(upload_to='media/')),
                ('contract', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='contr_clienti.Contract')),
            ],
        ),
    ]
