# Generated by Django 3.0.7 on 2020-07-22 06:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0006_auto_20200721_1412'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractscan',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
