# Generated by Django 3.0.7 on 2020-07-22 06:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0007_contractscan_uploaded_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractscan',
            name='uploaded_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
