# Generated by Django 3.0.7 on 2020-07-22 10:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0008_auto_20200722_0910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contract',
            name='document',
        ),
    ]
