# Generated by Django 3.0.7 on 2020-07-22 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0009_remove_contract_document'),
    ]

    operations = [
        migrations.AddField(
            model_name='contractscan',
            name='actaditional',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contr_clienti.ActAditional'),
        ),
    ]
