# Generated by Django 3.0.7 on 2020-08-04 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0010_contractscan_actaditional'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contractscan',
            name='contract',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='contr_clienti.Contract'),
        ),
    ]
