# Generated by Django 3.0.7 on 2020-08-14 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0011_auto_20200804_1256'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clienti',
            name='sediul_social',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sediu', to='contr_clienti.Adresa'),
        ),
    ]
