# Generated by Django 3.0.7 on 2020-08-17 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0012_auto_20200814_0950'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienti',
            name='reprezentant',
        ),
    ]
