# Generated by Django 3.0.7 on 2020-08-17 07:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0013_remove_clienti_reprezentant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienti',
            name='persoana_contact',
        ),
        migrations.AddField(
            model_name='persoanacontact',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contr_clienti.Clienti'),
        ),
        migrations.AddField(
            model_name='reprezentant',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contr_clienti.Clienti'),
        ),
    ]
