# Generated by Django 3.0.7 on 2020-08-17 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0014_auto_20200817_1009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reprezentant',
            name='functie',
            field=models.CharField(max_length=255),
        ),
    ]
