# Generated by Django 3.0.7 on 2020-08-17 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0015_auto_20200817_1427'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Adresa',
            new_name='AdresaSS',
        ),
        migrations.RemoveField(
            model_name='clienti',
            name='punct_de_lucru',
        ),
        migrations.CreateModel(
            name='AdresaPL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('localitate', models.CharField(max_length=255)),
                ('strada', models.CharField(max_length=255)),
                ('numar', models.CharField(max_length=255)),
                ('judet', models.CharField(max_length=255)),
                ('client', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contr_clienti.Clienti')),
            ],
            options={
                'verbose_name_plural': 'Adrese',
            },
        ),
    ]
