# Generated by Django 3.0.7 on 2020-08-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0016_auto_20200817_1449'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresapl',
            name='alte_detalii',
            field=models.CharField(default='detalii pl', max_length=255),
            preserve_default=False,
        ),
    ]
