# Generated by Django 3.0.7 on 2020-08-17 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0017_adresapl_alte_detalii'),
    ]

    operations = [
        migrations.AddField(
            model_name='adresapl',
            name='nume_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
