# Generated by Django 3.0.7 on 2020-08-18 06:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0018_adresapl_nume_pl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clienti',
            name='sediul_social',
        ),
        migrations.AddField(
            model_name='adresass',
            name='client',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contr_clienti.Clienti'),
        ),
    ]
