# Generated by Django 3.0.7 on 2020-08-20 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contr_clienti', '0019_auto_20200818_0940'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='aplicatiiinfo98',
            name='contravaloare_aplicatie',
        ),
        migrations.AlterField(
            model_name='adresass',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contr_clienti.Clienti'),
        ),
    ]
